gantt
  title Master Bath Remodel

  section Planning
    Water Distribution        :plan-water, 2d
    Duct Work                 :plan-ductwork, 2d
    Flooring                  :1d
  
  section Logistics
    Order Plumbing Parts      :after plan-water, 2h
    Order Ducting             :after plan-ductwork, 2h
  
  section Repairs
    Empty Cabinets            :empty-cabinets, 2d
    Remove Fixtures           :2d, after empty-cabinets, 2020-01-10
    Wiring                    :1d
    Plumbing                  :2d
    New Sheet Rock            :4d
  
  section Water Heater
    Frame Enclosure           :2d
    Drain Pan                 :1d
    Move WH                   :4h
    Wiring                    :2h
    Plumbing                  :1d
    Duct Work                 :4d
